import { Routes } from '@angular/router';
import { authGuard, customerProfileGuard, guestGuard, signupGuard } from './guards/auth.guard';

export const routes: Routes = [
  {
    path: '',
    pathMatch: 'full',
    loadComponent: () => import('./pages/landing/landing.component').then((m) => m.LandingComponent),
  },
  {
    path: 'login',
    loadComponent: () => import('./pages/login/login.component').then((m) => m.LoginComponent),
    canActivate: [guestGuard],
  },
  {
    path: 'signup',
    loadComponent: () => import('./pages/signup/signup.component').then((m) => m.SignupComponent),
    canActivate: [signupGuard],
  },
  {
    path: 'privacy',
    loadComponent: () => import('./pages/legal/legal.component').then((m) => m.LegalComponent),
    data: { doc: 'privacy' },
  },
  {
    path: 'terms',
    loadComponent: () => import('./pages/legal/legal.component').then((m) => m.LegalComponent),
    data: { doc: 'terms' },
  },
  {
    path: '',
    loadComponent: () => import('./layout/shell.component').then((m) => m.ShellComponent),
    canActivate: [authGuard, customerProfileGuard],
    children: [
      { path: 'home', loadComponent: () => import('./pages/home/home.component').then((m) => m.HomeComponent) },
      { path: 'profile', loadComponent: () => import('./pages/profile/profile.component').then((m) => m.ProfileComponent) },
      { path: 'settings', loadComponent: () => import('./pages/settings/settings.component').then((m) => m.SettingsComponent) },
      { path: 'addresses', loadComponent: () => import('./pages/profile/addresses.component').then((m) => m.AddressesComponent) },
      { path: 'health', loadComponent: () => import('./pages/health/health-hub.component').then((m) => m.HealthHubComponent) },
      { path: 'pets', loadComponent: () => import('./pages/pets/pets-list.component').then((m) => m.PetsListComponent) },
      { path: 'pets/new', loadComponent: () => import('./pages/pets/pet-form.component').then((m) => m.PetFormComponent) },
      { path: 'pets/:id', loadComponent: () => import('./pages/pets/pet-detail.component').then((m) => m.PetDetailComponent) },
      { path: 'pets/:id/edit', loadComponent: () => import('./pages/pets/pet-form.component').then((m) => m.PetFormComponent) },
      { path: 'pets/:id/health', loadComponent: () => import('./pages/pets/pet-health.component').then((m) => m.PetHealthComponent) },
      { path: 'pets/:id/timeline', loadComponent: () => import('./pages/pets/pet-timeline.component').then((m) => m.PetTimelineComponent) },
      { path: 'pets/:id/medications', loadComponent: () => import('./pages/care/medications.component').then((m) => m.MedicationsComponent) },
      { path: 'pets/:id/vaccinations', loadComponent: () => import('./pages/pets/pet-vaccinations.component').then((m) => m.PetVaccinationsComponent) },
      { path: 'pets/:id/conditions', loadComponent: () => import('./pages/pets/pet-conditions.component').then((m) => m.PetConditionsComponent) },
      { path: 'pets/:id/care-plans', loadComponent: () => import('./pages/pets/pet-care-plans.component').then((m) => m.PetCarePlansComponent) },
      { path: 'pets/:id/diagnostics', loadComponent: () => import('./pages/care/diagnostics.component').then((m) => m.DiagnosticsComponent) },
      { path: 'pets/:id/reminders', loadComponent: () => import('./pages/care/reminders.component').then((m) => m.RemindersComponent) },
      { path: 'pets/:id/calendar', loadComponent: () => import('./pages/pets/health-calendar.component').then((m) => m.HealthCalendarComponent) },
      { path: 'pets/:id/weight', loadComponent: () => import('./pages/pets/weight-trend.component').then((m) => m.WeightTrendComponent) },
      { path: 'pets/:id/passport', loadComponent: () => import('./pages/pets/pet-passport.component').then((m) => m.PetPassportComponent) },
      { path: 'pets/:id/documents', loadComponent: () => import('./pages/care/documents.component').then((m) => m.DocumentsComponent) },
      { path: 'book/new', loadComponent: () => import('./pages/book/book-wizard.component').then((m) => m.BookWizardComponent) },
      { path: 'bookings', loadComponent: () => import('./pages/bookings/bookings-list.component').then((m) => m.BookingsListComponent) },
      { path: 'bookings/:id', loadComponent: () => import('./pages/bookings/booking-detail.component').then((m) => m.BookingDetailComponent) },
      { path: 'bookings/:id/track', loadComponent: () => import('./pages/bookings/booking-track.component').then((m) => m.BookingTrackComponent) },
      { path: 'visits/:id', loadComponent: () => import('./pages/visits/visit-summary.component').then((m) => m.VisitSummaryComponent) },
      { path: 'notifications', loadComponent: () => import('./pages/notifications/notifications.component').then((m) => m.NotificationsComponent) },
      { path: 'medications', loadComponent: () => import('./pages/care/medications.component').then((m) => m.MedicationsComponent) },
      { path: 'reminders', loadComponent: () => import('./pages/care/reminders.component').then((m) => m.RemindersComponent) },
      { path: 'follow-ups', loadComponent: () => import('./pages/care/follow-ups.component').then((m) => m.FollowUpsComponent) },
      { path: 'documents', loadComponent: () => import('./pages/care/documents.component').then((m) => m.DocumentsComponent) },
      { path: 'support', loadComponent: () => import('./pages/care/support.component').then((m) => m.SupportComponent) },
      { path: 'intake', loadComponent: () => import('./pages/intelligence/smart-intake.component').then((m) => m.SmartIntakeComponent) },
      { path: 'assistant', loadComponent: () => import('./pages/intelligence/assistant.component').then((m) => m.AssistantComponent) },
      { path: 'emergency', loadComponent: () => import('./pages/care/emergency.component').then((m) => m.EmergencyComponent) },
      { path: 'emergencies/:id', loadComponent: () => import('./pages/care/emergency-status.component').then((m) => m.EmergencyStatusComponent) },
      { path: 'televet', loadComponent: () => import('./pages/care/televet.component').then((m) => m.TelevetComponent) },
      { path: 'diagnostics', loadComponent: () => import('./pages/care/diagnostics.component').then((m) => m.DiagnosticsComponent) },
      { path: 'diagnostics/:id', loadComponent: () => import('./pages/care/diagnostic-detail.component').then((m) => m.DiagnosticDetailComponent) },
      { path: 'second-opinion', loadComponent: () => import('./pages/care/second-opinion.component').then((m) => m.SecondOpinionComponent) },
    ],
  },
  { path: '**', redirectTo: '' },
];
